### ISSUE TITLE
画像が削られている

### ISSUE THREAD

**Issue by minahoku** [eggplants/getjump#23]
ダウンロードしたところすべての画像の右と下が数十ピクセル削られている
https://i.imgur.com/RPikCVm.png

度々々すみません よろしくお願いいたします

**Comment by eggplants** [comment]
参考:
https://shonenjumpplus.com/episode/13932016480028799982

<img width=300 src=https://cdn-ak-img.shonenjumpplus.com/public/page/2/10834108156642049326-4dc808b9f71724fb09b0ea7ce5047a7c></img>

---

今は4x4のピース部分を切り出して転置しているだけなので、もうちょっと賢く処理を書こうと思います。
