### ISSUE TITLE
unavailable gap

### ISSUE THREAD

**Issue by khoa301020** [eggplants/getjump#4]
pls add new height gap: 1920 & width gap: 1353 :<

**Comment by eggplants** [comment]
Thank you for yor report!
Please tell me the url.

**Comment by eggplants** [comment]
@khoa301020 /ping

**Comment by khoa301020** [comment]
> @khoa301020 /ping
Ah sorry, I forgot to check :<
The url is: `https://feelweb.jp/episode/3269754496548660763`

**Comment by eggplants** [comment]
Done. Please update.
