### ISSUE TITLE
合併号のタイトルがうまく取れていない

### ISSUE THREAD

**Issue by minahoku** [eggplants/getjump#49]
マガジン系統の雑誌で合併号の際タイトルがうまく取れていないせいでフォルダーが分かれてしまう

週刊少年マガジン２０２３年２・３号
https://comic-days.com/magazine/3270375685473882285

**Comment by eggplants** [comment]
正規表現で分割するのをやめて、別の手段での取得をするようにしたいところです。

**Comment by eggplants** [comment]
誌名単体は
https://comic-days.com/magazine/3270375685473882285.json にはなく、 https://comic-days.com/magazine/3270375685473882285 の `h1.series-header-title` から取得するか？

**Comment by eggplants** [comment]
漫画単体もそう

https://comic-days.com/episode/316112896948822224

**Comment by eggplants** [comment]
#50 で正規表現を直してます。あと、正規表現で分割する前に作品ページからシリーズタイトル(誌名)を取得できるか試して、取得できればそちらを使うようにしました。
